{
 "title": "Custom dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of calls to latest",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minitwit_elixir_custom_latest_count"
    }
   ]
  },
  {
   "title": "Number of messages and flagged messages",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minitwit_elixir_custom_messages_count{}"
    },
    {
     "expr": "minitwit_elixir_custom_flagged_messages_count{}"
    }
   ]
  },
  {
   "title": "Visits to the public timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "minitwit_elixir_custom_public_timeline_success{}"
    },
    {
     "expr": "minitwit_elixir_custom_public_timeline_not_authorized{}"
    }
   ]
  },
  {
   "title": "Number of api requests handled",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minitwit_elixir_custom_api_requests_count{}"
    }
   ]
  },
  {
   "title": "Number of users",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minitwit_elixir_custom_users_count"
    }
   ]
  },
  {
   "title": "Visits to user timeline",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "minitwit_elixir_custom_user_timeline_success{}"
    },
    {
     "expr": "minitwit_elixir_custom_user_timeline_not_authorized"
    }
   ]
  },
  {
   "title": "Register stats",
   "type": "stat",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minitwit_elixir_custom_register_success{}"
    },
    {
     "expr": "minitwit_elixir_custom_register_username_taken{}"
    },
    {
     "expr": "minitwit_elixir_custom_register_passwords_dont_match{}"
    },
    {
     "expr": "minitwit_elixir_custom_register_password_missing{}"
    },
    {
     "expr": "minitwit_elixir_custom_register_email_not_valid{}"
    },
    {
     "expr": "minitwit_elixir_custom_register_username_missing{}"
    }
   ]
  },
  {
   "title": "Tweets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "minitwit_elixir_custom_tweet_success"
    },
    {
     "expr": "minitwit_elixir_custom_tweet_not_authorized"
    },
    {
     "expr": "minitwit_elixir_custom_tweet_user_dont_exist"
    }
   ]
  },
  {
   "title": "Follow/unfollow",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "minitwit_elixir_custom_post_followers_follow_success"
    },
    {
     "expr": "minitwit_elixir_custom_post_followers_unfollow_success"
    },
    {
     "expr": "minitwit_elixir_custom_post_followers_follow_other_dont_exist"
    },
    {
     "expr": "minitwit_elixir_custom_post_followers_not_authorized"
    },
    {
     "expr": "minitwit_elixir_custom_post_followers_unfollow_other_dont_exist"
    },
    {
     "expr": "minitwit_elixir_custom_post_followers_user_dont_exist"
    },
    {
     "expr": "minitwit_elixir_custom_post_followers_action_missing"
    }
   ]
  },
  {
   "title": "Get follower requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minitwit_elixir_custom_get_followers_success"
    },
    {
     "expr": "minitwit_elixir_custom_get_followers_user_dont_exist"
    },
    {
     "expr": "minitwit_elixir_custom_get_followers_not_authorized"
    }
   ]
  }
 ]
}